name: "Arctic-Text2SQL-R1-7B"
model_path: "Snowflake/Arctic-Text2SQL-R1-7B"
model_type: "vllm"
generation_config:
  temperature: 0.0
  max_tokens: 512
  top_p: 1.0
  top_k: -1
vllm_config:
  tensor_parallel_size: 1
  gpu_memory_utilization: 0.9
  max_model_len: 8192
  trust_remote_code: true 